# Generated by Django 5.2.6 on 2025-09-13 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epi_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='equipamento',
            field=models.ForeignKey(default=15, on_delete=django.db.models.deletion.CASCADE, to='epi_management.equipamento'),
            preserve_default=False,
        ),
    ]
