# Generated by Django 5.2.6 on 2025-09-17 17:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("epi_management", "0002_emprestimo_equipamento"),
    ]

    operations = [
        migrations.RenameField(
            model_name="emprestimo",
            old_name="data_devolucao",
            new_name="data_devolucao_prevista",
        ),
        migrations.AddField(
            model_name="emprestimo",
            name="data_devolucao_efetiva",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="emprestimo",
            name="observacoes_devolucao",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="emprestimo",
            name="data_emprestimo",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="emprestimo",
            name="status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="epi_management.statusemprestimo",
            ),
        ),
    ]
